name: build

on:
  push:
    branches:
      - master
      - beta

jobs:
  build-docker:
    if: github.repository == 'jakowenko/double-take'
    runs-on: ubuntu-latest
    steps:
      - name: Set ENV to beta
        if: endsWith(github.ref, '/beta')
        run: |
          echo "TAG=beta" >> $GITHUB_ENV
          echo "ARCH=linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64" >> $GITHUB_ENV
      - name: Set ENV to latest
        if: endsWith(github.ref, '/master')
        run: |
          echo "TAG=latest" >> $GITHUB_ENV
          echo "ARCH=linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker Buildx (build)
        run: |
          docker buildx build \
            --platform ${ARCH} \
            --output "type=image,push=false" \
            --tag jakowenko/double-take:${TAG} \
            --file Dockerfile .
      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
      - name: Docker Buildx (push)
        run: |
          docker buildx build \
            --platform ${ARCH} \
            --output "type=image,push=true" \
            --tag jakowenko/double-take:${TAG} \
            --file Dockerfile .
      - name: Docker Check Manifest
        run: |
          docker run --rm mplatform/mquery jakowenko/double-take:${TAG}
      - name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json
