name: Build and Push Docker Image

on:
  push:
    branches:
      - '*'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ['','debug']
      fail-fast: false
    steps:
    - id: lowercaseRepo
      uses: ASzc/change-string-case-action@v5
      with:
        string: ${{ github.repository }}
    - name: Check out code
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Log in to the DockerHub
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Create short sha and tag
      shell: bash
      run: |
        echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
        if [[ "$GITHUB_REF" == "refs/heads/beta" ]]; then echo TAG=latest; else echo TAG="${GITHUB_REF##*/}"; fi >> $GITHUB_ENV
    - name: Build Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: .build/Dockerfile
        target: ${{ matrix.target }}
        push: true
        tags: |
          ghcr.io/${{ steps.lowercaseRepo.outputs.lowercase }}:${{ env.SHORT_SHA }}
          ghcr.io/${{ steps.lowercaseRepo.outputs.lowercase }}:${{ env.TAG }}${{ matrix.target }}
          ${{ steps.lowercaseRepo.outputs.lowercase }}:${{ env.SHORT_SHA }}
          ${{ steps.lowercaseRepo.outputs.lowercase }}:${{ env.TAG }}${{ matrix.target }}
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Sync
      uses: ms-jpq/sync-dockerhub-readme@v1
      if: github.ref == 'refs/heads/beta'
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository:  ${{ steps.lowercaseRepo.outputs.lowercase }}
        readme: "./README.md"
      