name: Build and Test Docker Image

on:
  workflow_dispatch:
  pull_request:
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
    - id: lowercaseRepo
      uses: ASzc/change-string-case-action@v5
      with:
        string: ${{ github.repository }}
    - name: Check out code
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Write dummy config
      run: |
        mkdir -p /tmp/config
        echo -e "detectors:\n  deepstack:\n    url: http://localhost:5000" > /tmp/config/config.yml
    - name: Build Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: .build/Dockerfile
        push: false
        load: true
        tags: |
          doubletake:latest
        platforms: ${{ matrix.platform }}
    - name: run docker Image
      run: |
        docker run --platform ${{ matrix.platform }} -d --rm -v /tmp/config:/.storage/config -p 3000:3000 doubletake:latest
    - name: Check http status code
      run: |
        sleep 30
        curl --show-error --connect-timeout 60 --max-time 120 --retry 20 --retry-all-errors http://localhost:3000/api/config
